version: '3.8'
services:
  backend:
    build:
      context: ./apps/backend
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    depends_on: []

  frontend:
    build:
      context: ./apps/frontend
    ports:
      - '4321:4321'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
